# Generated by Django 5.1.7 on 2025-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_type'),
        ('customers', '0002_remove_account_address_remove_contact_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='industry',
        ),
        migrations.AlterField(
            model_name='account',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'general'}, related_name='accounts', to='core.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='account',
            name='industry',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'industry'}, related_name='industry_accounts', to='core.tag', verbose_name='Industry'),
        ),
    ]
