# Generated by Django 5.1.7 on 2025-06-29 12:10

import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=apps.accounts.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail-Adresse')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nachname')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Mitarbeiter')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registriert am')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
            },
        ),
    ]
