# Generated by Django 5.1.7 on 2025-06-29 12:10

import apps.opportunities.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=apps.opportunities.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Opportunity Name')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount')),
                ('close_date', models.DateField(verbose_name='Expected Close Date')),
                ('stage', models.CharField(choices=[('QUALIFICATION', 'Qualification'), ('NEEDS_ANALYSIS', 'Needs Analysis'), ('PROPOSAL', 'Proposal/Price Quote'), ('NEGOTIATION', 'Negotiation/Review'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='QUALIFICATION', max_length=20, verbose_name='Stage')),
                ('probability', models.IntegerField(blank=True, help_text='Likelihood of closing the deal (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Probability (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='customers.account', verbose_name='Account')),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to='auth.group', verbose_name='Assigned Team')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL)),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='customers.contact', verbose_name='Primary Contact')),
                ('tags', models.ManyToManyField(blank=True, related_name='opportunities', to='core.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-close_date'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityProduct',
            fields=[
                ('id', models.UUIDField(default=apps.opportunities.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price Per Unit')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount (e.g., 10.5 for 10.5%)', max_digits=5, verbose_name='Discount (%)')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Total Line Price')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Product Line',
                'verbose_name_plural': 'Opportunity Product Lines',
            },
        ),
    ]
