# Generated by Django 5.1.7 on 2025-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('industry', 'Branche'), ('general', 'Allgemein')], default='general', max_length=20, verbose_name='Type'),
        ),
    ]
