# Generated by Django 5.1.7 on 2025-04-02 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('TASK', 'Task'), ('NOTE', 'Note Added')], max_length=20, verbose_name='Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Activity Date / Due Date')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('HELD', 'Held'), ('COMPLETED', 'Completed'), ('NOT_HELD', 'Not Held'), ('CANCELED', 'Canceled')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
